apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/mavazque/tekton-reversewords:547e0eb8ccc6276f313ebe63019d7ad22ee8ae32
        name: reverse-words
