apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reverse-words
  annotations:
    kubernetes.io/ingress.class: nginx
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  rules:
  - host: reversewords-dev.apps.ocp411.cd17.sandbox1535.opentlc.com
    http:
      paths:
      - backend:
          serviceName: reverse-words
          servicePort: http
