namespace: reverse-words-production
commonLabels:
  app: reversewords-prod
bases:
- github.com/mvazquezc/reverse-words-cicd?ref=config
resources:
- namespace.yaml
- ingress.yaml
patchesStrategicMerge:
- deployment.yaml
